version: '3.8'

services:
  email-automation:
    build: .
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
    volumes:
      - ./app.py:/app/app.py
    restart: unless-stopped
